version: "3.8"

services:
  db:
    platform: linux/amd64 # 맥
    image: mysql:5.7
    container_name: mydb
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - local-net

  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - local-net
    depends_on:
      - db

networks:
  local-net:
    driver: bridge